name: ryan-cahill-a0/fusionauth-app
author: Architect.io

interfaces:
  app: ${ services.app.interfaces.main.url }

dependencies:
  ryan-cahill-a0/fusionauth: latest

parameters:
  FUSIONAUTH_API_KEY:
    required: false
  FUSIONAUTH_CLIENT_ID:
    required: false
  FUSIONAUTH_CLIENT_SECRET:
    required: false

services:
  app:
    build:
      context: ./
    language: go
    description: Example Go service to test Fusionauth
    environment:
      PUBLIC_PORT: ${ services.app.interfaces.main.port }
      FA_HOST: ${ dependencies['ryan-cahill-a0/fusionauth'].interfaces.auth.host } # make sure referencing interfaces across components is documented
      FA_PORT: ${ dependencies['ryan-cahill-a0/fusionauth'].interfaces.auth.port }
      FA_CLIENT_ID: ${ parameters.FUSIONAUTH_CLIENT_ID }
      FA_CLIENT_SECRET: ${ parameters.FUSIONAUTH_CLIENT_SECRET }
      FA_API_KEY: ${ parameters.FUSIONAUTH_API_KEY }
    interfaces:
      main: 8080
