interfaces:
  app: ${ components['ryan-cahill-a0/fusionauth-app'].interfaces.app.url }
  auth: ${ components['ryan-cahill-a0/fusionauth'].interfaces.auth.url }

components:
  ryan-cahill-a0/fusionauth-app:
    extends: file:./architect.yml
    parameters:
      FUSIONAUTH_API_KEY: sJfDg7AU9p53kdVBryk2UarvAMcShZjdTqWAVqPBY2M
      FUSIONAUTH_CLIENT_ID: 8cc4c901-1852-4e62-a655-699f2c94ffdc
      FUSIONAUTH_CLIENT_SECRET: OshhDO0d1Y6Hrejsd697Yo4unTar_gI00fHiIASMZGc

  ryan-cahill-a0/fusionauth:
    extends: file:./fusionauth/architect.yml
    parameters:
      FUSIONAUTH_API_KEY: sJfDg7AU9p53kdVBryk2UarvAMcShZjdTqWAVqPBY2M
      FUSIONAUTH_CLIENT_ID: 8cc4c901-1852-4e62-a655-699f2c94ffdc
      FUSIONAUTH_CLIENT_SECRET: OshhDO0d1Y6Hrejsd697Yo4unTar_gI00fHiIASMZGc
      FUSIONAUTH_RUNTIME_MODE: development
      # TODO: flag to run migrations for prod?
