name: ryan-cahill-a0/fusionauth
author: Architect.io

interfaces:
  auth: ${ services.fusionauth.interfaces.http.url }

parameters:
  FUSIONAUTH_API_KEY:
    required: false
  FUSIONAUTH_CLIENT_ID:
    required: false
  FUSIONAUTH_CLIENT_SECRET:
    required: false
  FUSIONAUTH_RUNTIME_MODE:

services:
  fusionauth:
    image: fusionauth/fusionauth-app:latest
    description: Fusionauth service built from public image
    environment:
      DATABASE_URL: jdbc:${ services.db.interfaces.main.url }/${ services.db.environment.POSTGRES_DB }
      DATABASE_ROOT_USER: ${ services.db.environment.POSTGRES_USER }
      DATABASE_ROOT_PASSWORD: ${ services.db.environment.POSTGRES_PASSWORD }
      DATABASE_USER: ${ services.db.environment.POSTGRES_USER }
      DATABASE_PASSWORD: ${ services.db.environment.POSTGRES_PASSWORD }
      FUSIONAUTH_SEARCH_ENGINE_TYPE: database
      FUSIONAUTH_URL: ${ services.fusionauth.interfaces.http.url }
      FUSIONAUTH_RUNTIME_MODE: ${ parameters.FUSIONAUTH_RUNTIME_MODE }
      FUSIONAUTH_MEMORY: 256M # setting above architect kubernetes pod memory limit will result in the pod error Terminated: OOMKilled (we should make sure this is documented)
      FUSIONAUTH_API_KEY: ${ parameters.FUSIONAUTH_API_KEY }
      FUSIONAUTH_HTTP_PORT: ${ services.fusionauth.interfaces.http.port }
      ADMIN_USER_EMAIL: ryan.cahill@architect.io
      ADMIN_USER_PASSWORD: password
      FUSIONAUTH_KICKSTART: /usr/local/fusionauth/kickstart.json  # TODO seed to prod also
      FUSIONAUTH_CLIENT_ID: ${ parameters.FUSIONAUTH_CLIENT_ID }
      FUSIONAUTH_CLIENT_SECRET: ${ parameters.FUSIONAUTH_CLIENT_SECRET }
    interfaces:
      http: 9011
    language: java
    # debug:
    #   volumes:
    #     kickstart:
    #       host_path: ./kickstart.json # TODO seed to prod also (will be done in dockerfile)
    #       mount_path: /usr/local/fusionauth/kickstart.json

  db:
    image: postgres:9.6
    description: Postgres 9.6 backend for Fusionauth
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fusionauth
    interfaces:
      main:
        port: 5432
        protocol: postgresql
